[project]
name = "toolchest"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[dependency-groups]
dev = [
    "numpy>=2.3.1",
    "pytest>=8.4.1",
    "pytest-cov>=6.0.0",
]
